const Vos = require('./v_os');

console.log("\n<[ EOL() ]>---------");
console.log(vNodeOS.EOL());
console.log("\n<[ arch() ]>---------");
console.log(vNodeOS.arch());
console.log("\n<[ constants() ]>---------");
console.log(vNodeOS.constants());
console.log("\n<[ cpus() ]>---------");
console.log(vNodeOS.cpus());
console.log("\n<[ cpus() ]>---------");
console.log(vNodeOS.devNull());
console.log("\n<[ endianness() ]>---------");
console.log(vNodeOS.endianness());
console.log("\n<[ freemem() ]>---------");
console.log(vNodeOS.freemem());
console.log("\n<[ getPriority() ]>---------");
console.log(vNodeOS.getPriority());
console.log("\n<[ homedir() ]>---------");
console.log(vNodeOS.homedir());
console.log("\n<[ hostname() ]>---------");
console.log(vNodeOS.hostname());
console.log("\n<[ loadavg() ]>---------");
console.log(vNodeOS.loadavg());
console.log("\n<[ networkInterfaces() ]>---------");
console.log(vNodeOS.networkInterfaces());
console.log("\n<[ platform() ]>---------");
console.log(vNodeOS.platform());
console.log("\n<[ release() ]>---------");
console.log(vNodeOS.release());
console.log("\n<[ setPriority() ]>---------");
console.log(vNodeOS.setPriority(16));
console.log("\n<[ tmpdir() ]>---------");
console.log(vNodeOS.tmpdir());
console.log("\n<[ totalmem() ]>---------");
console.log(vNodeOS.totalmem());
console.log("\n<[ type() ]>---------");
console.log(vNodeOS.type());
console.log("\n<[ uptime() ]>---------");
console.log(vNodeOS.uptime());
console.log("\n<[ userInfo() ]>---------");
console.log(vNodeOS.userInfo());
console.log("\n<[ version() ]>---------");
console.log(vNodeOS.version());

