const v_os = require('./v_os')

console.log("\n<[ EOL() ]>---------");
console.log(v_os.EOL());
console.log("\n<[ arch() ]>---------");
console.log(v_os.arch());
console.log("\n<[ constants() ]>---------");
console.log(v_os.constants());
console.log("\n<[ cpus() ]>---------");
console.log(v_os.cpus());
console.log("\n<[ cpus() ]>---------");
console.log(v_os.devNull());
console.log("\n<[ endianness() ]>---------");
console.log(v_os.endianness());
console.log("\n<[ freemem() ]>---------");
console.log(v_os.freemem());
console.log("\n<[ getPriority() ]>---------");
console.log(v_os.getPriority());
console.log("\n<[ homedir() ]>---------");
console.log(v_os.homedir());
console.log("\n<[ hostname() ]>---------");
console.log(v_os.hostname());
console.log("\n<[ loadavg() ]>---------");
console.log(v_os.loadavg());
console.log("\n<[ networkInterfaces() ]>---------");
console.log(v_os.networkInterfaces());
console.log("\n<[ platform() ]>---------");
console.log(v_os.platform());
console.log("\n<[ release() ]>---------");
console.log(v_os.release());
console.log("\n<[ setPriority() ]>---------");
console.log(v_os.setPriority(16));
console.log("\n<[ tmpdir() ]>---------");
console.log(v_os.tmpdir());
console.log("\n<[ totalmem() ]>---------");
console.log(v_os.totalmem());
console.log("\n<[ type() ]>---------");
console.log(v_os.type());
console.log("\n<[ uptime() ]>---------");
console.log(v_os.uptime());
console.log("\n<[ userInfo() ]>---------");
console.log(v_os.userInfo());
console.log("\n<[ version() ]>---------");
console.log(v_os.version());

